- name: tags-block
  tags: zfs
  when: role_zfs
  block:

    - name: import tasks from install.yml
      import_tasks: install.yml
      tags: zfs_install
      when: import_zfs_install

    - name: import tasks from config.yml
      import_tasks: config.yml
      tags: zfs_config
      when: import_zfs_config

    - name: import tasks from monitoring.yml
      import_tasks: monitoring.yml
      tags: zfs_monitoring
      when: import_zfs_monitoring
