- block:

  - import_tasks: install.yml
    tags: zfs_install
    when: import_zfs_install

  - import_tasks: config.yml
    tags: zfs_config
    when: import_zfs_config

  - import_tasks: monitoring.yml
    tags: zfs_monitoring
    when: import_zfs_monitoring

  tags: zfs
